import { it, expect, vi } from 'vitest';
const api = vi.hoisted(() => ({ get:vi.fn().mockResolvedValue({}), set:vi.fn().mockResolvedValue(undefined), sendMessage:vi.fn().mockResolvedValue({ok:true,data:[{id:'cheap-vision',vision:true,context:1000000,pricing:{prompt:'0.0000001'}}]}) }));
vi.mock('wxt/browser',()=>({browser:{storage:{local:api},runtime:api}}));
import { mountSettings } from '../lib/settings-ui';
it('saves the actual form and populates vision model choices',async()=>{
  document.body.innerHTML='<main id="app"></main>';
  await mountSettings();
  (document.querySelector('[name="apiKey"]') as HTMLInputElement).value='mock-key';
  document.querySelector('form')!.dispatchEvent(new Event('submit',{cancelable:true}));
  await vi.waitFor(()=>expect(api.set).toHaveBeenCalled());
  expect(api.set.mock.calls[0]![0].settings.apiKey).toBe('mock-key');
  (document.querySelector('#models') as HTMLButtonElement).click();
  await vi.waitFor(()=>expect(document.querySelector('#image-models option')?.getAttribute('value')).toBe('cheap-vision'));
  expect(document.querySelector('#status')?.textContent).toContain('连接成功');
  const scope=document.querySelector<HTMLSelectElement>('#text-scope')!;expect(scope.value).toBe('viewport');scope.value='page';scope.dispatchEvent(new Event('change'));
  await vi.waitFor(()=>expect(api.set).toHaveBeenCalledWith({textScope:'page'}));
  const transparency=document.querySelector<HTMLInputElement>('#overlay-transparency')!,size=document.querySelector<HTMLInputElement>('#overlay-size')!;
  transparency.value='50';size.value='75';transparency.dispatchEvent(new Event('change'));
  await vi.waitFor(()=>expect(api.set).toHaveBeenCalledWith({overlayStyle:{transparency:50,size:75}}));
  expect(document.querySelector('#overlay-size-value')?.textContent).toBe('75%');
  (document.querySelector('#overlay-defaults') as HTMLButtonElement).click();
  await vi.waitFor(()=>expect(api.set).toHaveBeenCalledWith({overlayStyle:{transparency:0,size:100}}));
  (document.querySelector('#translation-context') as HTMLTextAreaElement).value='Test game';
  (document.querySelector('#translation-glossary') as HTMLTextAreaElement).value='Nora=诺拉';
  (document.querySelector('#save-profile') as HTMLButtonElement).click();
  await vi.waitFor(()=>expect(api.set).toHaveBeenCalledWith({translationProfile:{context:'Test game',glossary:'Nora=诺拉'}}));
});
